version: '3'

services:
  nginx:
    build: 
      context: nginx/
    container_name: nginx
    restart: unless-stopped
    tty: true
    networks: 
      - node-network
    ports: 
      - "80:80"
    depends_on:
      - app

  app:
    build: 
      context: node/
    container_name: app
    restart: unless-stopped
    tty: true
    volumes: 
      - ./node:/usr/src/app
    networks: 
      - node-network 
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      
